using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Example.Models;

namespace Example.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ILogger<AuthorsController> _logger;
        
        public AuthorsController(ILogger<AuthorsController> logger)
        {
            _logger = logger;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogDebug("GET Authors/Index");
            
            ViewBag.Message = "This page was generated by the HTTP GET handler in Controllers/Index.cs.";
            
            // The view expects a model of type Author, so for GET just send an empty model
            return View(new Author());
        }

        [HttpPost]
        public IActionResult Index(Author author)
        {
            _logger.LogDebug("POST Authors/Index");
            
            ViewBag.Message = "This page was generated by the HTTP POST handler in Controllers/Index.cs.";

            // You can check if the model requirements have been fullfilled using ModelState.
            // For now we'll just log a message that we got an invalid model.
            if (!ModelState.IsValid)
            {
                _logger.LogWarning("Received invalid model");
            }

            return View(author);
        }
    }
}